# CMake generated Testfile for 
# Source directory: /home/user/Desktop/assignment2/tests
# Build directory: /home/user/Desktop/assignment2/built/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[wrapping_integers_cmp]=] "/home/user/Desktop/assignment2/built/tests/wrapping_integers_cmp")
set_tests_properties([=[wrapping_integers_cmp]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;11;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[wrapping_integers_unwrap]=] "/home/user/Desktop/assignment2/built/tests/wrapping_integers_unwrap")
set_tests_properties([=[wrapping_integers_unwrap]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;12;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[wrapping_integers_wrap]=] "/home/user/Desktop/assignment2/built/tests/wrapping_integers_wrap")
set_tests_properties([=[wrapping_integers_wrap]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;13;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[wrapping_integers_roundtrip]=] "/home/user/Desktop/assignment2/built/tests/wrapping_integers_roundtrip")
set_tests_properties([=[wrapping_integers_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;14;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[byte_stream_construction]=] "/home/user/Desktop/assignment2/built/tests/byte_stream_construction")
set_tests_properties([=[byte_stream_construction]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;16;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[byte_stream_one_write]=] "/home/user/Desktop/assignment2/built/tests/byte_stream_one_write")
set_tests_properties([=[byte_stream_one_write]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;17;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[byte_stream_two_writes]=] "/home/user/Desktop/assignment2/built/tests/byte_stream_two_writes")
set_tests_properties([=[byte_stream_two_writes]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;18;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[byte_stream_capacity]=] "/home/user/Desktop/assignment2/built/tests/byte_stream_capacity")
set_tests_properties([=[byte_stream_capacity]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;19;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[byte_stream_many_writes]=] "/home/user/Desktop/assignment2/built/tests/byte_stream_many_writes")
set_tests_properties([=[byte_stream_many_writes]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;20;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[recv_connect]=] "/home/user/Desktop/assignment2/built/tests/recv_connect")
set_tests_properties([=[recv_connect]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;22;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[recv_transmit]=] "/home/user/Desktop/assignment2/built/tests/recv_transmit")
set_tests_properties([=[recv_transmit]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;23;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[recv_window]=] "/home/user/Desktop/assignment2/built/tests/recv_window")
set_tests_properties([=[recv_window]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;24;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[recv_reorder]=] "/home/user/Desktop/assignment2/built/tests/recv_reorder")
set_tests_properties([=[recv_reorder]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;25;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[recv_close]=] "/home/user/Desktop/assignment2/built/tests/recv_close")
set_tests_properties([=[recv_close]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;26;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[recv_special]=] "/home/user/Desktop/assignment2/built/tests/recv_special")
set_tests_properties([=[recv_special]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;27;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[fsm_stream_reassembler_cap]=] "/home/user/Desktop/assignment2/built/tests/fsm_stream_reassembler_cap")
set_tests_properties([=[fsm_stream_reassembler_cap]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;30;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[fsm_stream_reassembler_single]=] "/home/user/Desktop/assignment2/built/tests/fsm_stream_reassembler_single")
set_tests_properties([=[fsm_stream_reassembler_single]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;31;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[fsm_stream_reassembler_seq]=] "/home/user/Desktop/assignment2/built/tests/fsm_stream_reassembler_seq")
set_tests_properties([=[fsm_stream_reassembler_seq]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;32;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[fsm_stream_reassembler_dup]=] "/home/user/Desktop/assignment2/built/tests/fsm_stream_reassembler_dup")
set_tests_properties([=[fsm_stream_reassembler_dup]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;33;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[fsm_stream_reassembler_holes]=] "/home/user/Desktop/assignment2/built/tests/fsm_stream_reassembler_holes")
set_tests_properties([=[fsm_stream_reassembler_holes]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;34;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[fsm_stream_reassembler_many]=] "/home/user/Desktop/assignment2/built/tests/fsm_stream_reassembler_many")
set_tests_properties([=[fsm_stream_reassembler_many]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;35;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[fsm_stream_reassembler_overlapping]=] "/home/user/Desktop/assignment2/built/tests/fsm_stream_reassembler_overlapping")
set_tests_properties([=[fsm_stream_reassembler_overlapping]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;36;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
add_test([=[fsm_stream_reassembler_win]=] "/home/user/Desktop/assignment2/built/tests/fsm_stream_reassembler_win")
set_tests_properties([=[fsm_stream_reassembler_win]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/user/Desktop/assignment2/tests/CMakeLists.txt;7;add_test;/home/user/Desktop/assignment2/tests/CMakeLists.txt;37;add_test_exec;/home/user/Desktop/assignment2/tests/CMakeLists.txt;0;")
